apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: initiative-client-service
spec:
  selector:
    app: initiative-client-app
  ports:
    - protocol: "TCP"
      port: 80 # The port that the service is running on in the cluster
      targetPort: 3000 # The port exposed by the service
  type: LoadBalancer # type of the service. LoadBalancer indicates that our service will be external.
---
apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: initiative-client-app
spec:
  selector:
    matchLabels:
      app: initiative-client-app
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: initiative-client-app
    spec:
      containers:
        - name: initiative-client-app
          image: albinprivateregistry.azurecr.io/initiative-client # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 1024Mi
          ports:
            - containerPort: 3000 # The port that the container is running on in the cluster
