apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: initiative-client-app
spec:
  selector:
    matchLabels:
      app: initiative-client-app
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: initiative-client-app
    spec:
      containers:
        - name: initiative-client-app
          image: albinprivateregistry.azurecr.io/initiative-client:{{ .Values.dockerImageVersion }} # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 1024Mi
          ports:
            - containerPort: 3000 # The port that the container is running on in the cluster
